version: '2'

services:
  postgresql:
    container_name: pg
    image: postgres:12
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_PASSWORD=!Qsx4rgb'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

volumes:
  postgresql_data:
    driver: local
