version: '3.1'

services:
  db:
    container_name: mysql
    image: mysql:5.7.38
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - mysql:/var/log/mysql

volumes:
  mysql: {}