version: "2"
services:
  nacos:
    image: nacos/nacos-server:v2.1.0
    container_name: nacos
    environment:
    - PREFER_HOST_MODE=hostname
    - MODE=standalone
    
    ports:
    - "8848:8848"
    - "9848:9848"