version: '3.1'

services:

  redis:
    container_name: redis
    image: redis:5.0.14
    command: --save 600 1 --loglevel warning --requirepass youxin11
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis:/data
     

volumes:
  redis: {}